import type { Answer, Hotspot, SceneCrop, SceneDefinition } from "./types";

const FLOW_ART = "/exact/learning-flow.png";
const FLOW_SIZE = { sourceWidth: 1536, sourceHeight: 1024 } as const;

const answerHotspot = (label: string, answer: Answer, x: number, y: number, width: number, height: number): Hotspot => ({
  label,
  answer,
  value: answer,
  x,
  y,
  width,
  height,
  action: "answer",
});

const crop = (x: number, y: number, width: number, height: number): SceneCrop => ({ ...FLOW_SIZE, x, y, width, height });

export const scenes: readonly SceneDefinition[] = [
  {
    id: "title",
    image: "/exact/title.png",
    alt: "Princess and the Prepo. An interactive adventure to learn prepositions in a magical way. Start Adventure.",
    width: 512,
    height: 322,
    hotspots: [{ label: "Start Adventure", x: 51, y: 202, width: 152, height: 35, action: "start" }],
  },
  {
    id: "word-scattering",
    image: FLOW_ART,
    alt: "Word Scattering. Find the preposition among the scattered words. The target sentence is The cat is under the table.",
    width: 362,
    height: 321,
    crop: crop(13, 86, 362, 321),
    correct: "under",
    hotspots: [
      { label: "Choose THE", value: "the", x: 135, y: 75, width: 58, height: 38, action: "answer" },
      { label: "Choose CAT", value: "cat", x: 198, y: 75, width: 58, height: 38, action: "answer" },
      { label: "Choose IS", value: "is", x: 260, y: 75, width: 53, height: 38, action: "answer" },
      { label: "Choose UNDER, the preposition", value: "under", x: 150, y: 120, width: 87, height: 43, action: "answer" },
      { label: "Choose THE second tile", value: "the", x: 245, y: 120, width: 64, height: 43, action: "answer" },
      { label: "Choose TABLE", value: "table", x: 170, y: 168, width: 80, height: 42, action: "answer" },
    ],
  },
  {
    id: "sentence-reconstruction",
    image: FLOW_ART,
    alt: "Sentence Reconstruction. Tap the words in order to build: The cat is under the table.",
    width: 374,
    height: 321,
    crop: crop(388, 86, 374, 321),
    sequence: ["the-1", "cat", "is", "under", "the-2", "table", "period"],
    hotspots: [
      { label: "Word 1 THE", value: "the-1", x: 11, y: 80, width: 48, height: 42, action: "sequence" },
      { label: "Word 2 CAT", value: "cat", x: 61, y: 80, width: 48, height: 42, action: "sequence" },
      { label: "Word 3 IS", value: "is", x: 111, y: 80, width: 43, height: 42, action: "sequence" },
      { label: "Word 4 UNDER", value: "under", x: 157, y: 80, width: 59, height: 42, action: "sequence" },
      { label: "Word 5 THE", value: "the-2", x: 219, y: 80, width: 47, height: 42, action: "sequence" },
      { label: "Word 6 TABLE", value: "table", x: 269, y: 80, width: 62, height: 42, action: "sequence" },
      { label: "Word 7 PERIOD", value: "period", x: 334, y: 80, width: 34, height: 42, action: "sequence" },
    ],
  },
  {
    id: "picture-matching",
    image: FLOW_ART,
    alt: "Picture Matching. Match each cat picture with the sentence that describes its position.",
    width: 296,
    height: 321,
    crop: crop(775, 86, 296, 321),
    sequence: ["under", "on", "in"],
    hotspots: [
      { label: "Sentence: The cat is on the chair", value: "on", x: 150, y: 76, width: 132, height: 60, action: "sequence" },
      { label: "Sentence: The cat is under the table", value: "under", x: 150, y: 141, width: 132, height: 60, action: "sequence" },
      { label: "Sentence: The cat is in the box", value: "in", x: 150, y: 207, width: 132, height: 60, action: "sequence" },
    ],
  },
  {
    id: "storybook-intro",
    image: FLOW_ART,
    alt: "Interactive Storytelling. Read the story and answer questions based on what happens in the story.",
    width: 438,
    height: 321,
    crop: crop(1084, 86, 438, 321),
    hotspots: [{ label: "Begin interactive story", x: 340, y: 250, width: 70, height: 54, action: "advance" }],
  },
  {
    id: "river",
    image: "/exact/river.png",
    alt: "Across the River. The princess can walk blank the stones to cross the river. Choices: A, in; B, on; C, under.",
    width: 491,
    height: 322,
    correct: "on",
    hotspots: [
      answerHotspot("Answer A: IN", "in", 292, 197, 174, 27),
      answerHotspot("Answer B: ON", "on", 292, 227, 174, 27),
      answerHotspot("Answer C: UNDER", "under", 292, 257, 174, 27),
    ],
  },
  {
    id: "forest",
    image: "/exact/forest.png",
    alt: "Under the Tree. The princess can walk blank the fallen tree. Choices: A, on; B, under; C, next to.",
    width: 494,
    height: 322,
    correct: "under",
    hotspots: [
      answerHotspot("Answer A: ON", "on", 294, 201, 176, 27),
      answerHotspot("Answer B: UNDER", "under", 294, 232, 176, 27),
      answerHotspot("Answer C: NEXT TO", "next to", 294, 262, 176, 29),
    ],
  },
  {
    id: "treasure",
    image: "/exact/treasure.png",
    alt: "In the Treasure Room. The treasure is blank the chest. Choices: A, in; B, on; C, next to.",
    width: 512,
    height: 303,
    correct: "in",
    hotspots: [
      answerHotspot("Answer A: IN", "in", 323, 195, 162, 27),
      answerHotspot("Answer B: ON", "on", 323, 225, 162, 27),
      answerHotspot("Answer C: NEXT TO", "next to", 323, 254, 162, 27),
    ],
  },
  {
    id: "gate",
    image: "/exact/gate.png",
    alt: "Next to the Gate. The princess is standing blank the gate. Choices: A, on; B, next to; C, under.",
    width: 491,
    height: 303,
    correct: "next to",
    hotspots: [
      answerHotspot("Answer A: ON", "on", 305, 199, 163, 27),
      answerHotspot("Answer B: NEXT TO", "next to", 305, 228, 163, 27),
      answerHotspot("Answer C: UNDER", "under", 305, 257, 163, 27),
    ],
  },
  {
    id: "bridge",
    image: "/exact/bridge.png",
    alt: "Over the Bridge. The princess can walk blank the bridge. Choices: A, in; B, over; C, under.",
    width: 494,
    height: 303,
    correct: "over",
    hotspots: [
      answerHotspot("Answer A: IN", "in", 305, 199, 165, 27),
      answerHotspot("Answer B: OVER", "over", 305, 228, 165, 27),
      answerHotspot("Answer C: UNDER", "under", 305, 258, 165, 26),
    ],
  },
  {
    id: "garden",
    image: "/exact/garden.png",
    alt: "In the Garden. The princess is walking blank the flowers. Choices: A, in; B, on; C, next to.",
    width: 512,
    height: 293,
    correct: "in",
    hotspots: [
      answerHotspot("Answer A: IN", "in", 323, 194, 164, 27),
      answerHotspot("Answer B: ON", "on", 323, 224, 164, 27),
      answerHotspot("Answer C: NEXT TO", "next to", 323, 254, 164, 27),
    ],
  },
  {
    id: "puzzle-question",
    image: FLOW_ART,
    alt: "Puzzle Game. Where is the bunny? Choose the sentence that correctly describes the bunny behind the bush.",
    width: 480,
    height: 288,
    crop: crop(13, 421, 480, 288),
    correct: "behind",
    hotspots: [
      { label: "The bunny is in front of the bush", value: "in front", x: 228, y: 96, width: 232, height: 39, action: "answer" },
      { label: "The bunny is behind the bush", value: "behind", x: 228, y: 138, width: 232, height: 39, action: "answer" },
      { label: "The bunny is under the bush", value: "under", x: 228, y: 180, width: 232, height: 39, action: "answer" },
    ],
  },
  {
    id: "puzzle-word",
    image: FLOW_ART,
    alt: "Puzzle Game. Choose the correct word to complete: The cat is in the box.",
    width: 441,
    height: 288,
    crop: crop(506, 421, 441, 288),
    correct: "in",
    hotspots: [
      { label: "Choose ON", value: "on", x: 43, y: 235, width: 59, height: 42, action: "answer" },
      { label: "Choose UNDER", value: "under", x: 106, y: 235, width: 75, height: 42, action: "answer" },
      { label: "Choose IN", value: "in", x: 185, y: 235, width: 64, height: 42, action: "answer" },
      { label: "Choose BEHIND", value: "behind", x: 253, y: 235, width: 84, height: 42, action: "answer" },
    ],
  },
  {
    id: "puzzle-jigsaw",
    image: FLOW_ART,
    alt: "Puzzle Game. Rebuild the castle picture by selecting all three loose puzzle pieces.",
    width: 561,
    height: 288,
    crop: crop(961, 421, 561, 288),
    collectCount: 3,
    hotspots: [
      { label: "Puzzle piece one", value: "piece-1", x: 448, y: 48, width: 104, height: 73, action: "collect" },
      { label: "Puzzle piece two", value: "piece-2", x: 446, y: 126, width: 106, height: 72, action: "collect" },
      { label: "Puzzle piece three", value: "piece-3", x: 444, y: 204, width: 108, height: 72, action: "collect" },
    ],
  },
  {
    id: "progress-map",
    image: FLOW_ART,
    alt: "Your Progress. Word Scattering, Sentence Reconstruction, Picture Matching, Interactive Story and Puzzle Game are complete. Open the treasure chest to finish.",
    width: 889,
    height: 277,
    crop: crop(13, 724, 889, 277),
    hotspots: [{ label: "Open completion treasure chest", x: 720, y: 42, width: 155, height: 186, action: "advance" }],
  },
  {
    id: "completion",
    image: FLOW_ART,
    alt: "Well Done, Princess! You completed all activities and earned three stars. Choose Play Again or Back to Map.",
    width: 606,
    height: 277,
    crop: crop(916, 724, 606, 277),
    hotspots: [
      { label: "Play Again", x: 169, y: 224, width: 117, height: 40, action: "replay" },
      { label: "Back to Map", x: 318, y: 224, width: 127, height: 40, action: "next" },
    ],
  },
] as const;
