import type { SceneDefinition } from "./types";

const prep = (id: string, label = id.toUpperCase()) => ({ id, label });

export const scenes: readonly SceneDefinition[] = [
  { id: "title", chapter: "A New Adventure", interaction: "intro", objective: "Help Princess Prepo complete her adventure!", theme: "castle" },
  { id: "intro", chapter: "The Journey Begins", interaction: "intro", objective: "Princess Prepo wants to reach the magical flower garden. But the path is full of challenges! Help her discover where things are: IN, ON, UNDER, and NEXT TO.", theme: "castle" },
  { id: "river", chapter: "River Crossing", interaction: "choice", objective: "Princess Prepo wants to walk to the flower garden on the other side of the river. Help her choose the correct preposition so she can walk across safely!", question: "The princess can walk ______ the stones to cross the river.", choices: [prep("in"), prep("on"), prep("under")], correct: "on", sentence: "The princess walks ON the stones.", wrong: "Oops! That’s not correct. You can’t walk across!", hint: "Look at her feet. Which word means her feet touch the top of the stones?", oralPrompt: "What else can you stand on?", theme: "river" },
  { id: "forest", chapter: "Whispering Forest", interaction: "choice", objective: "A fallen tree blocks the forest path. Show Princess Prepo the safe way through.", question: "The princess can walk ______ the fallen tree.", choices: [prep("on"), prep("under"), prep("next", "NEXT TO")], correct: "under", sentence: "The princess walks UNDER the tree.", wrong: "That way is blocked. Let’s look again!", hint: "The path has a space below the tree.", oralPrompt: "Can you point under your desk?", theme: "forest" },
  { id: "treasure", chapter: "The Hidden Key", interaction: "choice", objective: "The garden gate is locked. Princess Prepo must find the golden key.", question: "The key is ______ the treasure chest.", choices: [prep("in"), prep("on"), prep("under")], correct: "in", sentence: "The key is IN the treasure chest.", wrong: "No key there yet. Try another place!", hint: "The chest must open before we can see the key.", oralPrompt: "What can you put in a box?", theme: "treasure" },
  { id: "gate", chapter: "The Garden Gate", interaction: "drag", objective: "Move Princess Prepo NEXT TO the statue to unlock the magical gate.", question: "Drag Princess beside the statue — or tap the glowing spot.", correct: "next", sentence: "The princess is NEXT TO the statue.", wrong: "Almost! Princess needs to stand beside the statue.", hint: "NEXT TO means at the side of something.", oralPrompt: "Who is sitting next to you?", theme: "gate" },
  { id: "bridge-word", chapter: "Magic Bridge", interaction: "choice", objective: "Complete the magic sentence to make the bridge glow!", question: "The princess is ______ the bridge.", choices: [prep("in"), prep("on"), prep("under"), prep("next", "NEXT TO")], correct: "on", sentence: "The princess is ON the bridge.", wrong: "The spell needs a different magic word.", hint: "Princess is standing on the bridge’s top surface.", theme: "bridge" },
  { id: "builder", chapter: "The Broken Spell", interaction: "builder", objective: "The magic spell is mixed up. Tap the words in the correct order!", question: "Build: The princess is under the bridge.", correct: "the princess|is|under|the bridge", sentence: "The princess is UNDER the bridge.", wrong: "Almost! Try the words in a different order.", hint: "Begin with ‘The princess’.", theme: "bridge-under" },
  { id: "hybrid", chapter: "Hands-On Challenge", interaction: "hybrid", objective: "Now use your Princess piece from the physical kit. Place Princess UNDER the bridge.", physicalPrompt: "Invite the pupil to say the full sentence after placing the piece.", theme: "camp" },
  { id: "final", chapter: "Final Challenge", interaction: "choice", objective: "One last puzzle will open the flower garden!", question: "Which sentence describes the picture?", choices: [prep("tree-in", "The princess is IN the tree."), prep("tree-next", "The princess is NEXT TO the tree."), prep("tree-under", "The princess is UNDER the tree."), prep("tree-on", "The princess is ON the tree.")], correct: "tree-next", sentence: "The princess is NEXT TO the tree.", wrong: "Look carefully at Princess and the tree.", hint: "She is standing beside the tree, not above or below it.", theme: "final" },
  { id: "ending", chapter: "Adventure Complete!", interaction: "ending", objective: "Great job! Princess Prepo reached the magical flower garden.", theme: "garden" },
];
